server:
  port: ${PORT}

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        event:
          merge:
            entity_copy_observer: allow
    database: mysql

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
---

spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    master:
      jdbcUrl: jdbc:mysql://db-ffarb-kr.vpc-pub-cdb.ntruss.com/skka?characterEncoding=utf8
      username: ${CLOUD_DB_USERNAME}
      password: ${CLOUD_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbcUrl: jdbc:mysql://db-ffaua-kr.vpc-pub-cdb.ntruss.com/skka?characterEncoding=utf8
      username: ${CLOUD_DB_USERNAME}
      password: ${CLOUD_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    user: ${CLOUD_DB_USERNAME}
    password: ${CLOUD_DB_PASSWORD}
    url: jdbc:mysql://db-ffarb-kr.vpc-pub-cdb.ntruss.com/skka?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    master:
      jdbcUrl: jdbc:mysql://localhost:3308/skka?characterEncoding=utf8
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbcUrl: jdbc:mysql://localhost:3308/skka?characterEncoding=utf8
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://localhost:3308/skka?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

---