spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:Skka-for-test;MODE=MYSQL;
    username: skka
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    database: h2
  flyway:
    enabled: true
    encoding: UTF-8
    user: skka
    password:
