server:
  port: ${port}

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: jdbc:mysql://db-f2rm7-kr.vpc-pub-cdb.ntruss.com/skka?characterEncoding=utf8
    username: ${cloud-db-user-id}
    password: ${cloud-db-user-password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    user: ${cloud-db-user-id}
    password: ${cloud-db-user-password}
    url: jdbc:mysql://db-f2rm7-kr.vpc-pub-cdb.ntruss.com/skka?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3308/skka?characterEncoding=utf8
    username: skka
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    user: skka
    password: 123456
    url: jdbc:mysql://localhost:3308/skka?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health