name: Sync Fork

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
  schedule:
  - cron:  '30 11,23 * * *'
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Taewoongjung'
          git config --global user.email 'aipooh8882@naver.com'
          # "git checkout develop" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/f-lab-edu/SSKA
          git fetch upstream
          git checkout develop
          git merge -Xtheirs upstream/develop
          git push origin develop
          # etc
