name: Sync Fork

on:
  push:
    branches: [ "develop" ]
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: trigger to NCP
        run: |
          curl --request POST \
          --url http://skka-loadbalancer-15716487-9d5197e0463b.kr.lb.naverncp.com/ncp/building_trigger/7834 \
          --header 'content-type: application/json' \
          --fail